#!/usr/bin/env bash

unrecognised_command() {
	echo "Unrecognised command: $@"
	exit 1
}

issue_get() {
	local issue_id="$1"

	curl -sS \
		-X GET \
		-H "Cookie: JSESSIONID=${jsessionid}" \
		"${jira_base_url}/issue/${issue_id}"
	}

issue_create() {
	curl -sS \
		-X POST \
		-H "Cookie: JSESSIONID=${jsessionid}" \
		-H 'Content-Type: application/json' \
		-d@- \
		"${jira_base_url}/issue" < "${filename:-/dev/stdin}"
}

issue_tosprint() {
	local issue_id="$1"
	local sprint_id="$2"

	curl -isS \
		-X POST \
		-H "Cookie: JSESSIONID=${jsessionid}" \
		-H 'Content-Type: application/json' \
		-d "{ \"issues\": [ \"${issue_id}\" ] }" \
		"${jira_agile_base_url}/sprint/${sprint_id}/issue"
}

handle_issue() {
	case $1 in
		get)
			shift
			issue_get "$@"
			;;

		create)
			shift
			issue_create "$@"
			;;

		tosprint)
			shift
			issue_tosprint "$@"
			;;

		*)
			unrecognised_command "$@"
	esac
}

sprint_get() {
	curl -sS \
		-X GET \
		-H "Cookie: JSESSIONID=${jsessionid}" \
		"${jira_agile_base_url}/board/${jira_board:-$default_jira_board}/sprint?state=active"
	}

handle_sprint() {
	case $1 in
		get)
			shift
			sprint_get "$@"
			;;

		*)
			unrecognised_command "$@"
	esac
}

new_bz() {
	local bz_id="$1"
	local issue_payload=$(mktemp)

	cat <<EOF > "$issue_payload"
{
  "fields": {
    "project": {
      "id": "$jira_project"
    },
    "summary": "BZ-${bz_id}",
    "issuetype": {
      "id": "10103"
    },
    "reporter": {
      "name": "$jira_username"
    },
    "description": "https://bugzilla.redhat.com/show_bug.cgi?id=${bz_id}",
    "components": [
      {
        "id": "$jira_component"
      }
    ]
  }
}
EOF

	issue_create < "$issue_payload"
}

new_bzs() {
	while getopts s o; do
		case "$o" in
			s) to_sprint=true ;;
		esac
	done

	local current_sprint=$(sprint_get | jq '.values[0].id')


	for bz_id in ${@:$OPTIND}; do
		local issue="$(mktemp)"

		new_bz "$bz_id" > "$issue"

		if [ "$to_sprint" = true ]; then
			issue_tosprint "$(jq -r '.key' "$issue")" "$current_sprint"
		else
			cat "$issue"
		fi
	done
}

print_help() {
	echo -e "Add a new Jira card in the sprint for a Bugzilla bug."
	echo
	echo -e "Required configuration:"
	echo
	echo -e "JIRA_USERNAME (or flag -u): Your Kerberos ID, without the '@redhat.com' part."
	echo -e "JIRA_JSESSIONID (or flag -p): Look into your browser's cookies."
	echo
	echo -e "Use:"
	echo -e "\t${0} bz [-s] <bz_id>..."
	echo
	echo -e "\t-s\t add the Jira card to the current sprint."
}

validate_configuration() {
	declare -a required_values=("jsessionid" "jira_username")
	local fail

	for val in "${required_values[@]}"; do
		local required=${!val}
		if [ -z "${required}" ]; then
			echo "Required variable '${val}' not found."
			fail='yes'
		fi
	done

	if ! [ -z $fail ]; then
		exit 1
	fi
}

# Set default configuration
default_jira_workspace='jira.coreos.com'
default_jira_board='361'
default_jira_project='14101'
default_jira_component='15800'

# Apply environment variables to configuration
jira_workspace="${JIRA_WORKSPACE:-$default_jira_workspace}"
jira_project="${JIRA_PROJECT:-$default_jira_project}"
jira_board="${JIRA_BOARD:-$default_jira_board}"
jsessionid="${JIRA_JSESSIONID}"
jira_username="${JIRA_USERNAME}"
jira_component="${JIRA_COMPONENT:-$default_jira_component}"

# Apply flags overrides to configuration
while getopts u:p:w:b:f:h o; do
	case "$o" in
		u) jira_username="$OPTARG"  ;;
		p) jsessionid="$OPTARG"     ;;
		w) jira_workspace="$OPTARG" ;;
		b) jira_board="$OPTARG"     ;;
		c) jira_component="$OPTARG" ;;
		f) filename="$OPTARG"       ;;
		h) print_help; exit 0       ;;
	esac
done

validate_configuration

jira_base_url="https://${jira_workspace:-$default_jira_workspace}/rest/api/2"
jira_agile_base_url="https://${jira_workspace:-$default_jira_workspace}/rest/agile/1.0"

# Process subcommands
case ${@:$OPTIND:1} in
	issue|i) handle_issue "${@:$(($OPTIND+1))}" ;;

	sprint|s) handle_sprint "${@:$(($OPTIND+1))}" ;;

	bugzilla|bz) new_bzs "${@:$(($OPTIND+1))}" ;;

	help) print_help; exit 0 ;;

	*) unrecognised_command "${@:$(($OPTIND+1))}"
esac
